/// Flutter icons LookingGlass
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LookingGlass
///      fonts:
///       - asset: fonts/LookingGlass.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LookingGlass {
  LookingGlass._();

  static const _kFontFam = 'LookingGlass';

  static const IconData crystal_ball = const IconData(0xe800, fontFamily: _kFontFam);
}
